### ISSUE TITLE
🐛 Bug Report: Signup is not working Network error

### ISSUE THREAD

**Issue by rajesh-avula** [appwrite/demo-todo-with-angular#34]
### 👟 Reproduction steps

1. Go to signup page
2. Enter the details and click on signup.
3. It's throwing Network error

Note : Before upgrading to angular v13 it was working as expected.

### 👍 Expected behavior

User should be able to signup and login

### 👎 Actual Behavior

User is not able to signup as it's displaying network error 

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by gewenyu99** [comment]
@brandonroberts has updated the app. This issue should be fixed now!

Please clear cache and try again, let us know if it's still a problem :)

**Comment by jwetzell** [comment]
Signup still seems to be an issue. This section of the `Account.Signup` account seem to be incorrect. [Lines 97-101](https://github.com/appwrite/demo-todo-with-angular/blob/c2389a2df303ac0cac42d8f0fbfd24d066381ba9/src/app/store/account/index.ts#L97-L101)

```     
let account = await Api.provider().account.create(
        email,
        password,
        name
);
```

the node library was updated back in January to reflect a change in the API where a userId can be provided so the `account.create` now takes `(userId, email, password, name)` adding `"unique()"` as the userId in the documentation will just generate an ID so the call would look like 

```     
let account = await Api.provider().account.create(
       'unique()',
        email,
        password,
        name
);
```

**Comment by brandonroberts** [comment]
@jwetzell yep, that's true. Must have missed that one in the update. Would you like to put in a PR to fix?

**Comment by jwetzell** [comment]
@brandonroberts Yeah I can put in a PR. Is just using the string 'unique()' alright for this demo app?

**Comment by brandonroberts** [comment]
@jwetzell Great! Yep, that's fine

**Comment by jwetzell** [comment]
@brandonroberts No problem, PR opened. I didn't reference this issue as not really sure this is the problem this issue was originally about. But I didn't experience any problems with signup after correcting this call.

**Comment by brandonroberts** [comment]
No problem. Might have been an isolated issue, but will be resolved with the PR either way 🙂
